### ISSUE TITLE
Errors in 1st tutorial (FPS character controller)

### ISSUE THREAD

**Issue by bastiaanschonhage** [fyrox-book/fyrox-book.github.io#16]
I ran into the following issues when trying to follow the tutorial described in 2.10.1.1. Character controller

1) Body Type of Rigid Body should be set to "Static" (in the properties) - not dynamic (for floor). If you do not do that, the floor will fall down ...

2) Copy/paste barrel - as I read it from the documentation, I should "barrel.FBX" and then copy/paste it. But I guess that is wrong. I probably should copy/paste the parent node (Rigid Body) that contains the barrel as a child.

3) In the code examples, there are (at least) two references to "GameEngine" but that should be Engine.
Example of wrong code: 
    impl GameState for Game {
        fn init(engine: &mut **GameEngine**) -> Self
  
4) the commit revision does not seem to exist for fyrox (only for rg3d)??
❯ cargo clean
❯ cargo update
    Updating git repository `https://github.com/FyroxEngine/Fyrox`
error: no matching package named `fyrox` found
location searched: https://github.com/FyroxEngine/Fyrox?rev=431c8dc16d75f7b8755a7ac6a7b43bd43fdcfca0

**Comment by mrDIMAS** [comment]
It should be fixed now in the latest commit.

**Comment by bastiaanschonhage** [comment]
Great, looks good to me!

**Comment by mrDIMAS** [comment]
Thanks! If you'll spot something else, please reopen the issue.
